[application]
redis_mode = "cluster"

[redis]                                                #单点
addr = "192.168.1.69:6379"                             #地址
password = "YcIPfs1829@129"                            #密码
dial_timeout = 10                                      #超时时间
pool_size = 20                                         #连接池大小

[rediscluster]                                         #redis集群
addrs = ["172.31.5.5:9001","172.31.5.5:9002","18.162.49.59:9001","18.162.49.59:9002","172.31.9.186:9001","172.31.9.186:9002"]
password = "YcIPfs1829@129"                            #密码
dial_timeout = 10                                      #超时时间
pool_size = 20                                         #连接池大小